#!/bin/sh

TMPFILE=/tmp/$(basename $0).$$.cmd

function do_mkimage {
echo Building script \""$1\"" - $2
mkimage -A arm -O linux -T script -C none -a 0 -e 0 -n "$1" -d $TMPFILE $2
}


cat <<EOF > $TMPFILE
setenv bootargs 'init=/bin/busybox sh console=tty0 console=ttyS2,115200n8 mpurate=600 nohz=off vram=16M omapfb.mode=dvi:640x480MR-16@60 omapdss.def_disp=dvi omapfb.vram=0:8M,1:4M,2:4M root=/dev/mmcblk0p2 rw rootfstype=ext3 rootwait mem=99M@0x80000000 mem=384M@0x88000000'
fatload mmc 0 0x82000000 uImage
bootm 0x82000000
EOF
do_mkimage "Shell only (VGA)" shell.scr

cat <<EOF > $TMPFILE
setenv bootargs 'console=tty0 console=ttyS2,115200n8 mpurate=600 nohz=off vram=16M omapfb.mode=dvi:1024x768MR-24@60 omapdss.def_disp=dvi omapfb.vram=0:8M,1:4M,2:4M root=/dev/mmcblk0p2 rw rootfstype=ext3 rootwait mem=99M@0x80000000 mem=384M@0x88000000'
fatload mmc 0 0x82000000 uImage
bootm 0x82000000
EOF
do_mkimage "Default (1024x768)" boot.scr

cat <<EOF > $TMPFILE
setenv bootargs 'console=tty0 console=ttyS2,115200n8 mpurate=600 nohz=off vram=16M omapfb.mode=dvi:hd720 omapdss.def_disp=dvi omapfb.vram=0:8M,1:4M,2:4M root=/dev/mmcblk0p2 rw rootfstype=ext3 rootwait mem=99M@0x80000000 mem=384M@0x88000000'
fatload mmc 0 0x82000000 uImage
bootm 0x82000000
EOF
do_mkimage "Default (720p)" boot-hd.scr

rm $TMPFILE

