#!/bin/sh
sox -n /tmp/sine.wav synth 1.0 sine 1000.0
echo "Connect audio out to audio in..."
sleep 3
arecord -t wav -c 2 -r 44100 -f S16_LE -v /tmp/sine-in.wav &
PID=$!
echo "Recording..."
sleep 1
echo "Playing..."
play /tmp/sine.wav
kill -15 $PID
sleep 1
echo "Connect the audio out to speakers..."
sleep 3
echo "Playing..."
play /tmp/sine-in.wav
sox /tmp/sine-in.wav -n stat
