#!/bin/sh
led = /sys/class/leds/beagleboard\:\:
usr0_triger = `cat ${led}usr0/trigger`
usr1_triger = `cat ${led}usr0/trigger`
echo none > ${led}usr0/trigger
echo none > ${led}usr0/trigger
echo 1 > ${led}usr0/brightness
echo 1 > ${led}usr1/brightness
sleep 3
echo 0 > ${led}usr0/brightness
sleep 3
echo 0 > ${led}usr1/brightness
sleep 3
echo $usr0_trigger > ${led}usr0/trigger
echo $usr1_trigger > ${led}usr0/trigger

