#!/bin/bash
TMPFILE=/tmp/$(basename $0).$$.pcm
arecord -t wav -c 2 -r 44100 -f S16_LE -v $TMPFILE &
PID=$!
sleep 1
echo "Recording..."
sleep 8
kill -15 $PID
sleep 1
aplay -t wav -c 2 -r 44100 -f S16_LE -v $TMPFILE
